allowBuilds:
  core-js-pure: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260525.1'
